//! Render-flow names, tags, spaces, groups, and request-time keys.

use super::{FrameResourceError, FrameResourceResult};
use std::{
    fmt,
    hash::{Hash, Hasher},
};

const AUTO_ID_BITS: u32 = 24;
const AUTO_ID_MASK: u32 = (1 << AUTO_ID_BITS) - 1;
const FNV1A_OFFSET_BASIS: u32 = 0x811c_9dc5;
const FNV1A_PRIME: u32 = 0x0100_0193;

pub const MAX_RENDER_FLOW_GROUPS: usize = 190;

#[derive(Clone, Copy, Debug)]
pub struct RenderFlowName {
    hash: u32,
    debug_name: Option<&'static str>,
}

impl RenderFlowName {
    pub const fn from_hash(hash: u32) -> Self {
        Self {
            hash,
            debug_name: None,
        }
    }

    pub fn from_static(name: &'static str) -> Self {
        Self {
            hash: stable_name_hash(name),
            debug_name: Some(name),
        }
    }

    pub fn dynamic(name: &str) -> Self {
        Self {
            hash: stable_name_hash(name),
            debug_name: None,
        }
    }

    pub const fn hash(self) -> u32 {
        self.hash
    }

    pub const fn debug_name(self) -> Option<&'static str> {
        self.debug_name
    }
}

impl From<&'static str> for RenderFlowName {
    fn from(name: &'static str) -> Self {
        Self::from_static(name)
    }
}

impl PartialEq for RenderFlowName {
    fn eq(&self, other: &Self) -> bool {
        self.hash == other.hash
    }
}

impl Eq for RenderFlowName {}

impl Hash for RenderFlowName {
    fn hash<H: Hasher>(&self, state: &mut H) {
        self.hash.hash(state);
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct RenderFlowSpace(u8);

impl RenderFlowSpace {
    pub const SHARED: Self = Self(0);
    pub const AUTOGENERATED: Self = Self(0xff);

    pub const fn new(index: u8) -> Self {
        Self(index)
    }

    pub const fn get(self) -> u8 {
        self.0
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct RenderFlowGroup(u16);

impl RenderFlowGroup {
    pub const fn new(index: u16) -> Self {
        Self(index)
    }

    pub const fn get(self) -> u16 {
        self.0
    }

    pub const fn index(self) -> usize {
        self.0 as usize
    }

    pub const fn is_valid(self) -> bool {
        self.index() < MAX_RENDER_FLOW_GROUPS
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct RenderFlowAutoId(u32);

impl RenderFlowAutoId {
    pub const NONE: Self = Self(0);

    pub fn new(raw: u32) -> FrameResourceResult<Self> {
        if raw <= AUTO_ID_MASK {
            Ok(Self(raw))
        } else {
            Err(FrameResourceError::InvalidOperation {
                operation: "RenderFlowAutoId::new",
                reason: "autogenerated render-flow id exceeds 24 bits",
            })
        }
    }

    pub const fn get(self) -> u32 {
        self.0
    }
}

#[derive(Clone, Copy)]
pub struct RenderFlowNameTag {
    hash: u32,
    flow_space: RenderFlowSpace,
    auto_id: RenderFlowAutoId,
}

impl RenderFlowNameTag {
    pub const INVALID: Self = Self {
        hash: 0,
        flow_space: RenderFlowSpace::SHARED,
        auto_id: RenderFlowAutoId::NONE,
    };

    pub fn new(name: RenderFlowName, flow_space: RenderFlowSpace) -> Self {
        Self::from_parts(name, flow_space, RenderFlowAutoId::NONE)
    }

    pub fn autogenerated(
        name: RenderFlowName,
        flow_space: RenderFlowSpace,
        auto_id: RenderFlowAutoId,
    ) -> Self {
        Self::from_parts(name, flow_space, auto_id)
    }

    pub const fn from_hash(hash: u32) -> Self {
        Self {
            hash,
            flow_space: RenderFlowSpace::SHARED,
            auto_id: RenderFlowAutoId::NONE,
        }
    }

    pub const fn hash(self) -> u32 {
        self.hash
    }

    pub const fn flow_space(self) -> RenderFlowSpace {
        self.flow_space
    }

    pub const fn auto_id(self) -> RenderFlowAutoId {
        self.auto_id
    }

    pub const fn is_valid(self) -> bool {
        self.hash != Self::INVALID.hash
    }

    fn from_parts(
        name: RenderFlowName,
        flow_space: RenderFlowSpace,
        auto_id: RenderFlowAutoId,
    ) -> Self {
        let scope_bits = ((flow_space.get() as u32) << AUTO_ID_BITS) | auto_id.get();
        Self::from_scoped_hash(name.hash() ^ scope_bits, flow_space, auto_id)
    }

    const fn from_scoped_hash(
        hash: u32,
        flow_space: RenderFlowSpace,
        auto_id: RenderFlowAutoId,
    ) -> Self {
        if hash == Self::INVALID.hash {
            Self {
                hash: 1,
                flow_space,
                auto_id,
            }
        } else {
            Self {
                hash,
                flow_space,
                auto_id,
            }
        }
    }
}

impl PartialEq for RenderFlowNameTag {
    fn eq(&self, other: &Self) -> bool {
        self.hash == other.hash
    }
}

impl Eq for RenderFlowNameTag {}

impl PartialOrd for RenderFlowNameTag {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        Some(self.cmp(other))
    }
}

impl Ord for RenderFlowNameTag {
    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
        self.hash.cmp(&other.hash)
    }
}

impl Hash for RenderFlowNameTag {
    fn hash<H: Hasher>(&self, state: &mut H) {
        self.hash.hash(state);
    }
}

impl fmt::Debug for RenderFlowNameTag {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("RenderFlowNameTag")
            .field("hash", &format_args!("{:#010x}", self.hash))
            .field("flow_space", &self.flow_space)
            .field("auto_id", &self.auto_id)
            .finish()
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct RequestTime {
    flow_group: RenderFlowGroup,
    index_in_group: u32,
}

impl RequestTime {
    pub const fn new(flow_group: RenderFlowGroup, index_in_group: u32) -> Self {
        Self {
            flow_group,
            index_in_group,
        }
    }

    pub const fn flow_group(self) -> RenderFlowGroup {
        self.flow_group
    }

    pub const fn index_in_group(self) -> u32 {
        self.index_in_group
    }
}

macro_rules! id_type {
    ($name:ident) => {
        #[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
        pub struct $name(u32);

        impl $name {
            pub const fn new(index: u32) -> Self {
                Self(index)
            }

            pub const fn get(self) -> u32 {
                self.0
            }
        }
    };
}

id_type!(ResourceRequestId);
id_type!(AllocationRequestId);
id_type!(FrameResourceAllocationId);

fn stable_name_hash(name: &str) -> u32 {
    let mut hash = FNV1A_OFFSET_BASIS;
    for byte in name.as_bytes() {
        hash ^= *byte as u32;
        hash = hash.wrapping_mul(FNV1A_PRIME);
    }
    hash
}
