use super::super::resources::{
    AllocationRequestId, FrameResourceAllocationId, RenderFlowAutoId, RenderFlowGroup,
    RenderFlowName, RenderFlowNameTag, RenderFlowSpace, RequestTime, ResourceAllocatorPhase,
    ResourceRequestId, ResourceUsage,
};

#[test]
fn resource_usage_flags_combine_and_test_bits() {
    let usage = ResourceUsage::READ | ResourceUsage::WRITE;

    assert!(usage.contains(ResourceUsage::READ));
    assert!(usage.contains(ResourceUsage::WRITE));
    assert!(!usage.contains(ResourceUsage::NO_DISCARD));
    assert!(usage.intersects(ResourceUsage::READ | ResourceUsage::NO_DISCARD));
    assert_eq!(
        (usage & ResourceUsage::READ).bits(),
        ResourceUsage::READ.bits()
    );
    assert!(ResourceUsage::NONE.is_empty());
}

#[test]
fn resource_usage_rejects_unknown_bits() {
    assert_eq!(
        ResourceUsage::from_bits(ResourceUsage::READ.bits()),
        Some(ResourceUsage::READ)
    );
    assert_eq!(ResourceUsage::from_bits(1 << 7), None);
    assert_eq!(
        ResourceUsage::from_bits_truncate(ResourceUsage::READ.bits() | (1 << 7)),
        ResourceUsage::READ
    );
}

#[test]
fn resource_allocator_phase_marks_consume() {
    assert!(ResourceAllocatorPhase::Consume.is_consume());
    assert!(!ResourceAllocatorPhase::PreConsume.is_consume());
}

#[test]
fn render_flow_tag_distinguishes_flow_spaces() {
    let color = RenderFlowName::from_static("color");

    let shared = RenderFlowNameTag::new(color, RenderFlowSpace::SHARED);
    let camera_a = RenderFlowNameTag::new(color, RenderFlowSpace::new(1));
    let camera_b = RenderFlowNameTag::new(color, RenderFlowSpace::new(2));

    assert_ne!(shared, camera_a);
    assert_ne!(camera_a, camera_b);
    assert!(shared.is_valid());
}

#[test]
fn render_flow_tag_is_stable_in_same_flow_space() {
    let first = RenderFlowNameTag::new(
        RenderFlowName::from_static("scene_color"),
        RenderFlowSpace::new(7),
    );
    let second = RenderFlowNameTag::new(
        RenderFlowName::dynamic("scene_color"),
        RenderFlowSpace::new(7),
    );

    assert_eq!(first, second);
    assert_eq!(first.hash(), second.hash());
}

#[test]
fn render_flow_name_debug_label_is_not_identity() {
    let with_debug = RenderFlowName::from_static("depth");
    let hash_only = RenderFlowName::from_hash(with_debug.hash());

    assert_eq!(with_debug, hash_only);
    assert_eq!(with_debug.debug_name(), Some("depth"));
    assert_eq!(hash_only.debug_name(), None);
}

#[test]
fn invalid_tag_is_distinct_from_real_tags() {
    let tag = RenderFlowNameTag::new(
        RenderFlowName::from_static("velocity"),
        RenderFlowSpace::SHARED,
    );

    assert!(!RenderFlowNameTag::INVALID.is_valid());
    assert_ne!(RenderFlowNameTag::INVALID, tag);
}

#[test]
fn constructed_tags_never_use_reserved_invalid_hash() {
    let tag = RenderFlowNameTag::new(RenderFlowName::from_hash(0), RenderFlowSpace::SHARED);

    assert!(tag.is_valid());
    assert_ne!(tag.hash(), RenderFlowNameTag::INVALID.hash());
}

#[test]
fn autogenerated_ids_produce_distinct_tags() {
    let name = RenderFlowName::from_static("temp");
    let flow_space = RenderFlowSpace::new(3);
    let first =
        RenderFlowNameTag::autogenerated(name, flow_space, RenderFlowAutoId::new(1).unwrap());
    let second =
        RenderFlowNameTag::autogenerated(name, flow_space, RenderFlowAutoId::new(2).unwrap());

    assert_ne!(first, second);
}

#[test]
fn autogenerated_id_is_limited_to_24_bits() {
    assert!(RenderFlowAutoId::new(0x00ff_ffff).is_ok());
    assert!(RenderFlowAutoId::new(0x0100_0000).is_err());
}

#[test]
fn request_time_sorts_by_group_then_index() {
    let group_a = RenderFlowGroup::new(1);
    let group_b = RenderFlowGroup::new(2);

    let mut times = [
        RequestTime::new(group_b, 0),
        RequestTime::new(group_a, 7),
        RequestTime::new(group_a, 2),
    ];
    times.sort();

    assert_eq!(times[0], RequestTime::new(group_a, 2));
    assert_eq!(times[1], RequestTime::new(group_a, 7));
    assert_eq!(times[2], RequestTime::new(group_b, 0));
    assert_eq!(times[0].flow_group(), group_a);
    assert_eq!(times[0].index_in_group(), 2);
}

#[test]
fn id_wrappers_are_copy_values() {
    let request = ResourceRequestId::new(11);
    let allocation_request = AllocationRequestId::new(12);
    let allocation = FrameResourceAllocationId::new(13);

    let copied_request = request;
    let copied_allocation_request = allocation_request;
    let copied_allocation = allocation;

    assert_eq!(copied_request.get(), 11);
    assert_eq!(copied_allocation_request.get(), 12);
    assert_eq!(copied_allocation.get(), 13);
}
