use super::super::resources::{
    ExternalFrameResourceId, FrameBufferDesc, FrameResourceAllocationId, FrameResourceAllocator,
    FrameResourceDesc, FrameTextureDesc, ImportedFrameResource, RenderFlowAutoId, RenderFlowGroup,
    RenderFlowName, RenderFlowNameTag, RenderFlowSpace, ResourceAllocatorPhase, ResourceRequest,
    ResourceUsage,
};
use crate::{RenderAppPlugin, RenderDevice};
use bevy_app::App;
use wgpu::{
    BufferDescriptor, BufferUsages, Extent3d, TextureDescriptor, TextureDimension, TextureFormat,
    TextureUsages,
};

fn tag(name: &'static str) -> RenderFlowNameTag {
    RenderFlowNameTag::new(RenderFlowName::from_static(name), RenderFlowSpace::SHARED)
}

fn flow_group(index: u16) -> RenderFlowGroup {
    RenderFlowGroup::new(index)
}

fn texture_desc(width: u32) -> FrameTextureDesc {
    FrameTextureDesc::new(TextureDescriptor {
        label: None,
        size: Extent3d {
            width,
            height: 32,
            depth_or_array_layers: 1,
        },
        mip_level_count: 1,
        sample_count: 1,
        dimension: TextureDimension::D2,
        format: TextureFormat::Rgba8Unorm,
        usage: TextureUsages::TEXTURE_BINDING | TextureUsages::RENDER_ATTACHMENT,
        view_formats: &[],
    })
}

fn buffer_desc(size: u64) -> FrameBufferDesc {
    FrameBufferDesc::new(BufferDescriptor {
        label: None,
        size,
        usage: BufferUsages::COPY_DST | BufferUsages::STORAGE,
        mapped_at_creation: false,
    })
}

fn declare_texture(name: &'static str, width: u32) -> ResourceRequest {
    ResourceRequest::Declare {
        tag: tag(name),
        desc: FrameResourceDesc::Texture(texture_desc(width)),
    }
}

fn use_begin(name: &'static str) -> ResourceRequest {
    ResourceRequest::UseBegin {
        tag: tag(name),
        usage: ResourceUsage::WRITE,
    }
}

fn use_end(name: &'static str) -> ResourceRequest {
    ResourceRequest::UseEnd { tag: tag(name) }
}

fn render_device() -> RenderDevice {
    let mut app = App::new();
    app.add_plugins(RenderAppPlugin);
    app.world().resource::<RenderDevice>().clone()
}

fn create_texture(
    render_device: &RenderDevice,
    desc: &FrameTextureDesc,
) -> (wgpu::Texture, wgpu::TextureView) {
    let descriptor = desc
        .concrete_descriptor_for_shape(desc.max_capacity_shape())
        .unwrap();
    let texture = render_device.0.create_texture(&descriptor);
    let view = texture.create_view(&wgpu::TextureViewDescriptor::default());
    (texture, view)
}

fn create_buffer(render_device: &RenderDevice, desc: &FrameBufferDesc) -> wgpu::Buffer {
    let descriptor = desc
        .concrete_descriptor_for_shape(desc.max_capacity_shape())
        .unwrap();
    render_device.0.create_buffer(&descriptor)
}

fn preconsume_and_resolve(allocator: &mut FrameResourceAllocator, requests: &[ResourceRequest]) {
    allocator
        .set_phase(ResourceAllocatorPhase::PreConsume)
        .unwrap();
    for request in requests {
        allocator
            .record_request(flow_group(0), request.clone())
            .unwrap();
    }
    allocator
        .set_phase(ResourceAllocatorPhase::Resolve)
        .unwrap();
}

#[test]
fn request_stream_dump_reports_group_index_kind_and_tag() {
    let mut allocator = FrameResourceAllocator::new();
    allocator
        .set_phase(ResourceAllocatorPhase::PreConsume)
        .unwrap();
    allocator
        .record_request(flow_group(0), declare_texture("color", 64))
        .unwrap();

    let dump = allocator.diagnostics().dump_request_stream();

    assert!(dump.contains("group=0"));
    assert!(dump.contains("index=0"));
    assert!(dump.contains("kind=Declare"));
    assert!(dump.contains("tag=hash="));
    assert!(dump.contains("flow_space=shared"));
    assert!(dump.contains("auto_id=none"));
}

#[test]
fn request_stream_dump_formats_camera_flow_spaces_and_temp_tags() {
    let mut allocator = FrameResourceAllocator::new();
    let temp_tag = RenderFlowNameTag::autogenerated(
        RenderFlowName::from_static("scratch"),
        RenderFlowSpace::new(3),
        RenderFlowAutoId::new(42).unwrap(),
    );
    allocator
        .set_phase(ResourceAllocatorPhase::PreConsume)
        .unwrap();
    allocator
        .record_request(
            flow_group(0),
            ResourceRequest::Declare {
                tag: temp_tag,
                desc: FrameResourceDesc::Texture(texture_desc(64)),
            },
        )
        .unwrap();

    let dump = allocator.diagnostics().dump_request_stream();

    assert!(dump.contains("flow_space=camera:3"));
    assert!(dump.contains("auto_id=temp:42"));
}

#[test]
fn replay_mismatch_report_identifies_expected_and_actual_requests() {
    let allocator = FrameResourceAllocator::new();
    let expected = declare_texture("color", 64);
    let actual = use_begin("color");

    let report = allocator
        .diagnostics()
        .replay_mismatch_report(0, 3, &expected, &actual);

    assert!(report.contains("group=0"));
    assert!(report.contains("index=3"));
    assert!(report.contains("expected_kind=Declare"));
    assert!(report.contains("actual_kind=UseBegin"));
}

#[test]
fn lifetime_and_timeline_dumps_show_request_times_and_events() {
    let imported =
        ImportedFrameResource::texture(ExternalFrameResourceId::new(22), texture_desc(64));
    let requests = vec![
        declare_texture("a", 64),
        declare_texture("b", 64),
        use_begin("a"),
        use_end("a"),
        use_begin("b"),
        use_end("b"),
        ResourceRequest::Swap {
            a: tag("a"),
            b: tag("b"),
        },
        ResourceRequest::Import {
            tag: tag("history"),
            resource: imported,
        },
    ];
    let mut allocator = FrameResourceAllocator::new();
    preconsume_and_resolve(&mut allocator, &requests);

    let lifetimes = allocator.diagnostics().dump_lifetimes();
    let timelines = allocator.diagnostics().dump_tag_timelines();

    assert!(lifetimes.contains("start=group:0 index:0"));
    assert!(lifetimes.contains("end=group:0 index:"));
    assert!(timelines.contains("kind=Swap"));
    assert!(timelines.contains("kind=Import"));
}

#[test]
fn pool_dump_distinguishes_owned_imported_and_external_swap_resources() {
    let render_device = render_device();
    let mut allocator = FrameResourceAllocator::new();
    let texture_desc = texture_desc(64);
    let buffer_desc = buffer_desc(1024);

    allocator
        .resource_pool_mut()
        .create_owned_texture(
            FrameResourceAllocationId::new(1),
            texture_desc.clone(),
            &render_device,
        )
        .unwrap();
    let (texture, view) = create_texture(&render_device, &texture_desc);
    allocator
        .resource_pool_mut()
        .import_texture(
            FrameResourceAllocationId::new(2),
            texture_desc.clone(),
            texture,
            view,
        )
        .unwrap();
    let buffer = create_buffer(&render_device, &buffer_desc);
    allocator
        .resource_pool_mut()
        .insert_external_swap_buffer(FrameResourceAllocationId::new(3), buffer_desc, buffer)
        .unwrap();

    let dump = allocator.diagnostics().dump_pool();

    assert!(dump.contains("ownership=Owned"));
    assert!(dump.contains("ownership=Imported"));
    assert!(dump.contains("ownership=ExternalSwap"));
    assert!(dump.contains("resource_kind=Texture"));
    assert!(dump.contains("resource_kind=Buffer"));
    assert!(!dump.contains("0x"));
}

#[test]
fn reuse_decision_dump_includes_rejection_reasons() {
    let render_device = render_device();
    let mut allocator = FrameResourceAllocator::new();
    allocator
        .resource_pool_mut()
        .create_owned_texture(
            FrameResourceAllocationId::new(50),
            texture_desc(128),
            &render_device,
        )
        .unwrap();
    let requests = vec![
        declare_texture("color", 256),
        use_begin("color"),
        use_end("color"),
    ];

    preconsume_and_resolve(&mut allocator, &requests);
    allocator.resolve_frame_resources(&render_device).unwrap();

    let dump = allocator.diagnostics().dump_reuse_decisions();

    assert!(dump.contains("rejection request="));
    assert!(dump.contains("reason=DescriptorIncompatible"));
}

#[test]
fn eviction_and_oversized_dumps_explain_cached_pool_pressure() {
    let render_device = render_device();
    let mut allocator = FrameResourceAllocator::new();
    allocator
        .resource_pool_mut()
        .create_owned_texture(
            FrameResourceAllocationId::new(7),
            texture_desc(128),
            &render_device,
        )
        .unwrap();
    allocator
        .resource_pool_mut()
        .mark_non_cacheable(FrameResourceAllocationId::new(7))
        .unwrap();

    let eviction = allocator.diagnostics().dump_eviction_state();
    let oversized = allocator
        .diagnostics()
        .dump_oversized_cached_allocations_for(&FrameResourceDesc::Texture(texture_desc(64)));

    assert!(eviction.contains("evicts_on_next_cleanup=true"));
    assert!(oversized.contains("oversized_cached_allocations"));
}
